# Generated by Django 5.1.3 on 2024-11-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='full_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='pub_date',
            new_name='publication_date',
        ),
    ]
